### ISSUE TITLE
User story for External Partners

### ISSUE THREAD

**Issue by Ley94** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#101]
- [x] Upload csv file for database

**Comment by chilipadiboy** [comment]
Upload Data file for Therapist (CSV):
NRIC (therapist),NRIC (patient),  (Permission (read modify), filename
Upload Data file for Therapist notes (CSV):
NRIC (therapist), NRIC (patient), (Permission (read modify), filename

**Comment by chilipadiboy** [comment]
Upload data file for patient-therapist relationships
<Irrelevant>
Upload data file for record permissions
Default read

The hospital would need to issue its own permission and therapist as such there will be no permissions set for these things

**Comment by Zhiyuan-Amos** [comment]
Hmm their system is implemented very differently from ours haha. Their system: Every `data file`, `notes` and `patient records` have to specify RW.

For ours, we're assuming that only the `Therapist` treating the `Patient` has RW capabilities. @chk1994 do you foresee any problems with this?

**Comment by Zhiyuan-Amos** [comment]
@chilipadiboy I'm wondering how to fit their specifications into our system.

**Comment by chilipadiboy** [comment]
> @chilipadiboy I'm wondering how to fit their specifications into our system.

They are using some tinyint to determine read /mondify etc. But when they give us it will have default read permissions
