### ISSUE TITLE
Make server accessible only through client

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#16]
Secure TLS tunnel. This helps in the transport of JWT by ensuring secrecy and authentication.

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 at #35 you mentioned about MFA? What's that regarding ah.

**Comment by gjlam95** [comment]
Using the ble for login on top of password
