### ISSUE TITLE
Improve server's security

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#17]
- [x] Server accessible only through https 
- [x] Server accessible only through Client (cannot connect with server through cURL etc from other sources)

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 just to double confirm, the HTTPS will be settled by Adeeb and yourself is it?

**Comment by gjlam95** [comment]
thats right. latest update is that our site has been redirected to https le but we cant access our ports. adeeb gonna check with the admin ppl what's wrong

**Comment by Zhiyuan-Amos** [comment]
@gngster gentle reminder
