### ISSUE TITLE
Unused method

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#48]
@gjlam95 

https://github.com/IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend/blob/4e82d069e39466e495c74ecc181ad32638b75949/backend-server/src/main/java/org/cs4239/team1/protectPMLeefrontendserver/controller/UserController.java#L45-L53

Do you require this method?

**Comment by gjlam95** [comment]
nope!

**Comment by Zhiyuan-Amos** [comment]
@chk1994 confirm no need this method liao
