### ISSUE TITLE
User story for Admin for Login

### ISSUE THREAD

**Issue by gngster** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#49]
1. Admin already has an account in our healthcare database + a tag under his skin.
2. Admin logs in with his credentials. 
3. Admin can see a "Create Account" page - which is actually our current "Sign Up" page. 
4. So this "Create Account" page will be for admins to create an account for any patient/anyone.
5. Signup/create account page now requires an additional field for public key for admin to fill in and pass the tag to the new registered user.

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 take note of this

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 is this done?

**Comment by gjlam95** [comment]
Point 5 not done yet. Unless jiahui's latest PR fixes it which I ain't too sure. @gngster ?
