### ISSUE TITLE
User story for every other user

### ISSUE THREAD

**Issue by gngster** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#50]
They can only see a login page and not a create account page. Admin would already have created an account for them

**Comment by Zhiyuan-Amos** [comment]
@gngster can you record the discussion we had? Since prof mentioned that he wanted us to document our decisions, so this is an example of a decision that we made because the current way of signing up has issues:
1. Fake users can register using other people's NRICs
1. New method is more streamlined (admin register for user & pass the tag to user VS user register -> admin add PK for user & pass tag to user)

**Comment by Zhiyuan-Amos** [comment]
cc: @gjlam95 

For login page, just to double confirm, are we performing authentication for all fields at the same time i.e.:
1. Username
1. Password
1. Tag
1. Role

Or are we doing verification of:
1. Username
1. Password
1. Role

Then load to another page, then verify tag?

I think the benefits of doing the former are:
1. 1 lesser HTML page to redirect to
1. Harder to guess password: Attacker cannot attempt brute force attack on guessing passwords without the tag (attacker shouldn't be having anyone else tag)
1. 1 lesser method to write for backend huehue

**Comment by gngster** [comment]
guys :( we are unable to do this... i just tried on the front end! so at first i was thinking there will be "connect tag to login" button that the user will click on after he fills up all his details and we send the username, password and role to the server and only when it comes back then we start the connect to bluetooth tag and get everything going and only when that is done then we successfully log the user into the system. and if it fails, we just say that something went wrong right. but now i realised that because of the security of web bluetooth api, the user has to use a user gesture to indicate he wants to start the bluetooth communication. so we can't call it for them. so that means that there probably has to be 2 buttons instead - one that says "connect to bluetooth tag" and another that says "log in"... and we probably might need 2 html pages after all.... because we still first need to get the user details like nric to know which user is trying to log in so we need the user to click some sort of submit button so we know he is done writing all his credentials and only when he is done then he can click on the connect to bluetooth tag button. is this understandable?

**Comment by gngster** [comment]
ahhh wait i think i found a workaround

**Comment by gngster** [comment]
also i think if we want to filter the devices that show up by name as well, means we can only tie the tag to one specific user... cos the name of the tag will be the nric of the person - what do you all think? or maybe can ask prof on monday

**Comment by gngster** [comment]
okay conclusion of matter is : because right now our team only gets to work with 2 tags, the tag will have a general name, instead of the nric of the user. but if the user really each has a tag, the tag that appears will only be the nric of the user.

**Comment by Zhiyuan-Amos** [comment]
> filter the devices

@gngster can you put our discussion for this in the docs also :>
