### ISSUE TITLE
shift tag verification to backend

### ISSUE THREAD

**Issue by gngster** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#51]
Step #1: use this library https://github.com/str4d/ed25519-java  and let me know what are the parameters and return values for the 3 operations - Generate keypair, Sign message, Verify signature. 

Step #2: backend should send signature(nonce + H(randomNum)) and  nonce + H(randomNum) to browser and send it all as an array with numbers.

**Comment by Zhiyuan-Amos** [comment]
Jia Hui can you take a look:

```java
/**
 * Initializes this object for verification. If this method is called
 * again with a different argument, it negates the effect
 * of this call.
 *
 * @param publicKey the public key of the identity whose signature is
 * going to be verified.
 *
 * @exception InvalidKeyException if the key is invalid.
 */
public final void initVerify(PublicKey publicKey)
        throws InvalidKeyException {
    engineInitVerify(publicKey);
    state = VERIFY;

    if (!skipDebug && pdebug != null) {
        pdebug.println("Signature." + algorithm +
            " verification algorithm from: " + this.provider.getName());
    }
}
```

I think I should be calling this method because I have the public key?

```java
/**
 *  To efficiently verify all the data in one shot, if it is available,
 *  use this method, which will avoid copying the data.
 *
 * Same as:
 *<pre>
 *  setParameter(ONE_SHOT_MODE)
 *  update(data)
 *  ok = verify(signature)
 *</pre>
 *
 * @param data the message that was signed
 * @param signature of the message
 * @return true if the signature is valid, false otherwise
 * @throws SignatureException if update() already called
 * @see #ONE_SHOT_MODE
 */
public boolean verifyOneShot(byte[] data, byte[] signature) throws SignatureException {
    return verifyOneShot(data, 0, data.length, signature, 0, signature.length);
}
```

Then I think I'll call this method to perform verification. So I'll need `data` and `signature` from you.

**Comment by gngster** [comment]
yup!!

**Comment by gngster** [comment]
Api call to server #1:  
GET call
**Content sent to server**: so the content sent to the server is whatever that is in the login function in APIUtils. 
**Return content to browser**: in the response from the server, the browser expects to get a signature, message and the nonce that server has used. 

So that the browser can split it up into 20 bytes sized packets and send with the nonce over. 

Then the browser waits for the tag to talk back to it and respond with tag's signature and msg.

Api call to server #2:
POST call
**Content sent to server**: so the content sent to server is the signature and message of tag
**Return content to browser**: success or failure. 
Upon success, the user logs in and on failure, the user does not log in.
