### ISSUE TITLE
User story for Admin functionalities

### ISSUE THREAD

**Issue by gjlam95** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#60]
1. Admin is able retrieve every user's profile in the following format (NRIC, Name, Role, Phone number, Email)
2. Admin is able to delete any user

**Comment by gjlam95** [comment]
A 'transaction' consists of interactions between the client and server, eg. signing up a new user, requesting to download stuff etc.

@Ley94 maybe can advise if I am right to say that?

**Comment by Zhiyuan-Amos** [comment]
Can we create another issue for logging? Logging is a whole big thing altogether, simply because our backend hasn't logged anything in the first place.

**Comment by Zhiyuan-Amos** [comment]
Fixed by #84
