### ISSUE TITLE
User story for Patient

### ISSUE THREAD

**Issue by gjlam95** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#82]
Fixes #141 
- [x] Can view his own health data
- [x] Can create, view, edit his own notes
- [x] Can view the notes created by his therapist(s) if its allowed for him to view
- [x] Can allow/disallow the therapist who uploaded his health data to view it (default is allow)
- [ ] Can allow/disallow specific therapists to view his notes (default is disallow)

**Comment by Zhiyuan-Amos** [comment]
@chk1994 will you be doing this?

**Comment by chk1994** [comment]
Mm let me try to complete the patient-therapist relationship first

**Comment by Zhiyuan-Amos** [comment]
This is done is #123, but we don't support the following feature:

> Can allow/disallow specific therapists to view his notes (default is disallow)

Cos it seems like there's no use for this. Is it ok with you Guang Jun?
