### ISSUE TITLE
FileController: support additional features

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#88]
- [x] Clashes in file names
- [x] Download video

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 wanna check with you:

1. Is every image/video file tagged to a record?
1. What API do you exactly need?

**Comment by gjlam95** [comment]
1. Yes
2. With regards to upload & download, I need an API to upload a file that's tagged to a patient, after which the download link will be reflected under his records upon successful upload.

@Ley94 anything else to add on?

**Comment by Zhiyuan-Amos** [comment]
Ok so to confirm: `Therapist` uploads a `Record`, which may or may not have `images`/`videos` tagged to it. 

@chk1994 I will probs need to check with you on the `Record` part. Just fyi.

**Comment by gjlam95** [comment]
Yup
