### ISSUE TITLE
File types available for uploading

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#90]
.jpg, .png, ~~.csv,~~ .mp4

Edit: `.csv` to be stored as a text in `content` column.
![image](https://user-images.githubusercontent.com/19281514/47141514-72d13800-d2f3-11e8-961f-89779fd72c4c.png)

**Comment by Zhiyuan-Amos** [comment]
@gjlam95 so when the user clicks on a link, a new tab will appear and display the video / image?

**Comment by gjlam95** [comment]
thats right
