### ISSUE TITLE
User story for Front-desk

### ISSUE THREAD

**Issue by Ley94** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#99]
Add user(s) of any role except Administrator. (Front-desk role is for Team 2 to use)

**Comment by Zhiyuan-Amos** [comment]
Note to self: set registration permissions only for admin and external partner

**Comment by Ley94** [comment]
Do you mean frontdesk instead?

**Comment by gjlam95** [comment]
Reminder that external partner can perform front desk
